//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.13
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 531a9f67-17be-46f7-acf2-fcc16eb38c5e aws-my-sample-app-android-v0.13";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:9ed363c3-2f51-4a8f-8ab7-3a411d22c17d";
    // Google Client ID for Web application
    public static final String GOOGLE_CLIENT_ID =
        "935044408554-qevt3rkihu4p8kbjv3v9j8fpu3ermvum.apps.googleusercontent.com";
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "195476758384";
    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:us-east-1:104807864716:app/GCM/parkassist_MOBILEHUB_119988226";
    public static final Regions AMAZON_SNS_REGION =
         Regions.fromName("us-east-1");
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:us-east-1:104807864716:parkassist_alldevices_MOBILEHUB_119988226";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {};
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_hFJy2zPVF";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "5lltsqpkscbdamc2iis99iucl7";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "vnmpt11ahme6rph3gsggcv12qfu8o7760raah2s7h7hj84577fc";
}
